export const ROWS = [
  {
    id: "a",
    name: "あ行",
    unlocked: true,
    kana: [
      { id: "a-hira", hira: "あ", kata: "ア", script: "hira", romaji: "a", row: "a", confusables: ["o-hira"] },
      { id: "i-hira", hira: "い", kata: "イ", script: "hira", romaji: "i", row: "a", confusables: ["ri-hira"] },
      { id: "u-hira", hira: "う", kata: "ウ", script: "hira", romaji: "u", row: "a", confusables: ["ra-hira"] },
      { id: "e-hira", hira: "え", kata: "エ", script: "hira", romaji: "e", row: "a", confusables: ["n-hira"] },
      { id: "o-hira", hira: "お", kata: "オ", script: "hira", romaji: "o", row: "a", confusables: ["a-hira"] },
      { id: "a-kata", hira: "あ", kata: "ア", script: "kata", romaji: "a", row: "a", confusables: ["ma-kata"] },
      { id: "i-kata", hira: "い", kata: "イ", script: "kata", romaji: "i", row: "a", confusables: ["ni-kata"] },
      { id: "u-kata", hira: "う", kata: "ウ", script: "kata", romaji: "u", row: "a", confusables: ["wa-kata"] },
      { id: "e-kata", hira: "え", kata: "エ", script: "kata", romaji: "e", row: "a", confusables: ["ko-kata"] },
      { id: "o-kata", hira: "お", kata: "オ", script: "kata", romaji: "o", row: "a", confusables: ["a-kata"] },
    ],
  },
  { id: "ka", name: "か行", unlocked: false, kana: [] },
  { id: "sa", name: "さ行", unlocked: false, kana: [] },
  { id: "ta", name: "た行", unlocked: false, kana: [] },
  { id: "na", name: "な行", unlocked: false, kana: [] },
  { id: "ha", name: "は行", unlocked: false, kana: [] },
  { id: "ma", name: "ま行", unlocked: false, kana: [] },
  { id: "ya", name: "や行", unlocked: false, kana: [] },
  { id: "ra", name: "ら行", unlocked: false, kana: [] },
  { id: "wa", name: "わ行", unlocked: false, kana: [] },
  { id: "n", name: "ん", unlocked: false, kana: [] },
];

export const ALL_ROMAJI = [
  "a",
  "i",
  "u",
  "e",
  "o",
  "ka",
  "ki",
  "ku",
  "ke",
  "ko",
  "sa",
  "shi",
  "su",
  "se",
  "so",
  "ta",
  "chi",
  "tsu",
  "te",
  "to",
  "na",
  "ni",
  "nu",
  "ne",
  "no",
  "ha",
  "hi",
  "fu",
  "he",
  "ho",
  "ma",
  "mi",
  "mu",
  "me",
  "mo",
  "ya",
  "yu",
  "yo",
  "ra",
  "ri",
  "ru",
  "re",
  "ro",
  "wa",
  "wo",
  "n",
];

export const KANA_BY_ID = Object.fromEntries(
  ROWS.flatMap((row) => row.kana).map((kana) => [kana.id, kana]),
);
